version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: AKP
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: backend
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:80"

volumes:
  postgres-data:
